
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://103.218.157.98:3306/toolmarket?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: kykim
  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
    cache : false
  devtools:
    livereload:
      enabled: true
#  jpa:
#    show-sql: true
#    properties:
#      hibernate.hbm2ddl.auto: update
mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
  type-aliases-package: com.toolmarket.toolmarket.dto
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

#server:
#  port: 80
#  compression:
#    enabled: true













